
name: Send File to Salesforce
on:
  push:
    branches:
      - master
jobs:
  send_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get -y install jq
      - name: Get Salesforce OAuth2 Token
        id: get_token
        run: |
          CLIENT_ID=3MVG9n_HvETGhr3A7RsBhmC5FTKle1C59pGSGAIky.5sEsZQq04PtYyZ.tuz7Jl7KDmBZP9JQfipVnyOz.O0V
          CLIENT_SECRET=9F611F06C496C62C34C322D298F3599FAA2FE8D3812736900E048C9E5D263111
          USERNAME=assest1_codeninja@epam.com
          PASSWORD=asset@2025
          TOKEN_RESPONSE=$(curl -d "grant_type=password" -d "client_id=$CLIENT_ID" -d "client_secret=$CLIENT_SECRET" -d "username=$USERNAME" -d "password=$PASSWORD" "https://test.salesforce.com/services/oauth2/token")
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          echo "{access_token}={$ACCESS_TOKEN}" >> $GITHUB_OUTPUT
      - name: Send File to Salesforce
        run: |
          FILE_PATH=ScannerResult.csv
          SALESFORCE_URL=https://epam-2e1-dev-ed.develop.lightning.force.com/services/apexrest/uploadScanner
          ACCESS_TOKEN="${{ steps.get_token.outputs.access_token }}"
          curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" -H "Content-Type: multipart/form-data" -F "file=@$FILE_PATH" $SALESFORCE_URL
